obj-$(CONFIG_AM_ATBM8869) += atbm8878_fe.o

atbm8878_fe-objs = atbm887x.o atbmfrontend.o  ###log_calc.o atbmdvbc.o atbm884x.o tuner_func.o i2c_func.o

##atbm8859_fe-objs += si2176/si2176_func.o

EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core
